### ISSUE TITLE
Heroku Demo Down

### ISSUE THREAD

**Issue by sascha1337** [t3chnoboy/amazon-product-api#57]
http://watchlist-koa.herokuapp.com/amazon/Shoes?title=nike%20nevis
![screen shot 2016-09-04 at 23 04 26](https://cloud.githubusercontent.com/assets/12372821/18233861/f4bbd260-72f3-11e6-9d2c-db6cb9a5e32e.png)

**Comment by Lowell130** [comment]
can i see some demo of te code, please
ty

**Comment by Lowell130** [comment]
any working code demo?

**Comment by JuanCrg90** [comment]
Hi I just created a mirror for the heroku app

https://juancrg90-watchlist-koa.herokuapp.com/amazon/Shoes?title=nike
https://juancrg90-watchlist-koa.herokuapp.com/amazon/DVD?title=alien
https://juancrg90-watchlist-koa.herokuapp.com/amazon/VideoGames?title=streets%20of%20rage

regards.

**Comment by Lowell130** [comment]
how i can see in action?

**Comment by masterT** [comment]
It's an API, there is no UI.

**Comment by Lowell130** [comment]
i am  newbie and really want know how it work, any help?

**Comment by JuanCrg90** [comment]
@Lowell130  check the examples directory https://github.com/t3chnoboy/amazon-product-api/tree/master/examples there you can check how to the API works.

 you need to create an access key, you can see that in the following link. 

http://docs.aws.amazon.com/AWSECommerceService/latest/GSG/GettingStarted.htm

@masterT this issue is covered with the mirror links. should we close it?

**Comment by Lowell130** [comment]
@JuanCrg90 Hello yes, already i have amazon key but i not understand how use javascript in html page, thank you

**Comment by JuanCrg90** [comment]
@Lowell130 this package is for use in your backend, you need to create a server with some node.js  framework like Express.js, Meteor or, Koa. the Amazon keys are very delicate, don't expose it.

**Comment by masterT** [comment]
Yes, I will close it.

**Comment by Lowell130** [comment]
@JuanCrg90 thank you!
